hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })

hl.workspace_rule({ workspace = "special:spotify", on_created_empty = "spotify" })
hl.workspace_rule({ workspace = "special:obs", on_created_empty = "obs" })
hl.workspace_rule({ workspace = "special:gamestore", on_created_empty = "steam" })

-- Generated by hyprmoncfg; hyprland.lua requires it again for its flat-require check.
if package.searchpath("monitors", package.path) then
  require("monitors")
end
