-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Ancor Communications Inc VG248 F3LMQS027757",
  mode = "1920x1080@60.00",
  position = "0x0",
  scale = 1,
  transform = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Microstep MSI G273Q CA8A641300127",
  mode = "2560x1440@164.84",
  position = "1080x100",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Microstep MSI G273Q CA8A641300127" })
hl.workspace_rule({ workspace = "2", monitor = "desc:Microstep MSI G273Q CA8A641300127" })
hl.workspace_rule({ workspace = "3", monitor = "desc:Microstep MSI G273Q CA8A641300127" })
hl.workspace_rule({ workspace = "4", monitor = "desc:Microstep MSI G273Q CA8A641300127" })
hl.workspace_rule({ workspace = "5", monitor = "desc:Microstep MSI G273Q CA8A641300127" })
hl.workspace_rule({ workspace = "6", monitor = "desc:Ancor Communications Inc VG248 F3LMQS027757" })
hl.workspace_rule({ workspace = "7", monitor = "desc:Ancor Communications Inc VG248 F3LMQS027757" })
hl.workspace_rule({ workspace = "8", monitor = "desc:Ancor Communications Inc VG248 F3LMQS027757" })
hl.workspace_rule({ workspace = "9", monitor = "desc:Ancor Communications Inc VG248 F3LMQS027757" })
hl.workspace_rule({ workspace = "10", monitor = "desc:Ancor Communications Inc VG248 F3LMQS027757" })
