general {
  after_sleep_cmd=hyprctl dispatch 'hl.dsp.dpms("on")'
  before_sleep_cmd=hyprlock --no-fade-in --grace 0
  ignore_dbus_inhibit=false
  lock_cmd=hyprlock
}

listener {
  on-timeout=hyprlock
  timeout=900
}

listener {
  on-resume=hyprctl dispatch 'hl.dsp.dpms("on")'
  on-timeout=hyprctl dispatch 'hl.dsp.dpms("off")'
  timeout=1200
}
